version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./test-sql-2:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mysql